### ISSUE TITLE
2주차 주제(운영체제, 네트워크)

### ISSUE THREAD

**Issue by SemiHyeon** [Newbiz-Coders/CStudy#2]
### 📌 네트워크
- [x] [월] : **TCP 3-way handshake와 4-way handshake**의 차이점과 각각의 역할을 설명하고, 이 과정들이 네트워크 통신에서 중요한 이유를 설명해주세요.
- [x] [목] : **TCP에서 흐름 제어**를 어떻게 구현하는지 설명해주세요.

### 📌 운영체제
- [x] [화] : **인터럽트의 정의**와 인터럽트가 **발생 했을때의 처리 과정**에 대해 설명해주세요
- [x] [목] : 시스템 콜의 **특징**을 설명해 주세요

**Comment by devstar1223** [comment]
## 시스템 콜과 라이브러리 함수의 차이

- 시스템 콜은 운영 체제와 직접 상호작용 한다.
- 반면 라이브러리 함수는 사용자 공간에서 동작하며, **시스템 콜을 간접적으로 호출하게 된다.**
    - `printf()` 의 라이브러리 함수 호출시 → 내부적으로 `write()` 시스템 콜을 호출하여 표준 출력을 처리한다.
    - 
## 흐름제어는 오류제어/혼잡제어와 어떻게 다를까?

- 흐름제어는 데이터의 송신 속도가 수신측의 버퍼크기에 비해 너무 빨라 수신측이 다 받지 못할때 문제를 해결하기 위한 방법이다.
- 오류제어는 송신측의 데이터 패킷또는 수신측의 확인 응답(ACK)가 제대로 전송되지 않거나, 소실되었을때 문제를 해결하기 위한 방법이다.
- 혼잡제어는 병목현상 등과 같이 네트워크에 데이터 패킷이 많아져 전송이 제대로 되지 않을때 문제를 해결하기 위한 방법이다.

**Comment by hye-on** [comment]
- **TCP에서 Receive Window가 가득 찼을 때 송신 측은 어떻게 동작하나요?**
    - **답변**: 송신 측은 수신 측의 Receive Window 크기를 보고 더 이상 데이터를 전송하지 않고 대기합니다. 수신 측이 버퍼를 비우고 새로운 Receive Window 크기를 송신 측에 알리면 전송을 재개합니다.
    스터디 답변 : 데이터를 보내지 않고 대기합니다.
    
    
-  **wait이 필요한 이유는 무엇인가요?**
    - **답변**: `wait`은 부모 프로세스가 자식 프로세스의 종료를 기다리게 하여, 자식 프로세스가 종료되지 않은 상태에서 부모가 자원을 해제하거나 종료하지 않도록 동기화를 보장합니다.
    - 스터디 답변 : 문맥교환

**Comment by SemiHyeon** [comment]
시스템 콜

### 흐름 제어가 없는 프로토콜에는 어떤 문제가 생기나요?
### 답변:

흐름 제어가 없으면 송신 측이 너무 많은 데이터를 보내 **수신 측 버퍼가 오버플로우**되어 데이터 손실이 발생할 수 있습니다.

TCP는 이를 방지하기 위해 흐름 제어를 도입했으며, 흐름 제어가 없는 UDP 같은 프로토콜은 이를 애플리케이션 수준에서 관리해야 합니다.

스터디 답변: 데이터의 전송 속도를 조절하지 못해 누락이되는 패킷이 발생할 것 같습니다.

### 사용자 모드와 커널 모드는 무엇이며, 왜 분리되어 있나요?

### 답변:

사용자 모드는 응용 프로그램이 실행되는 제한된 권한의 모드이고, 커널 모드는 운영 체제가 시스템 자원과 하드웨어를 직접 제어하는 권한을 가진 모드입니다. 이 둘은 시스템의 안정성과 보안을 위해 분리되어 있습니다. 사용자 모드에서 하드웨어를 직접 제어하면 시스템이 손상될 위험이 있기 때문에, 중요한 작업은 커널 모드에서만 처리됩니다.

**Comment by emoee** [comment]
윈도우 크기가 0일 때 송신자는 무엇을 해야 하나요?
윈도우 크기가 0인 경우, 수신자가 데이터를 처리할 수 없는 상태이므로 송신자는 대기해야 합니다. 송신자는 계속해서 ACK를 기다리며, 수신자가 데이터를 처리하여 버퍼 공간이 확보되면, 송신자는 다시 데이터를 전송할 수 있게 됩니다. 송신자는 윈도우 크기가 0일 때 데이터를 보내지 않으며, 수신자가 윈도우 크기를 갱신할 때까지 기다립니다.

시스템 콜을 사용하지 않고 하드웨어에 직접 접근할 수는 없나요?
사용자 프로그램은 보안과 안정성 문제로 하드웨어에 직접 접근할 수 없습니다. 운영체제의 커널은 하드웨어 자원에 대한 직접적인 접근을 관리하고, 사용자 프로그램은 커널을 통해 간접적으로 하드웨어와 상호작용합니다. 이를 통해 사용자 프로그램이 시스템 자원에 대한 제어를 잃지 않도록 하고, 다른 프로그램에 영향을 미치지 않도록 보장할 수 있습니다. 시스템 콜은 커널과의 인터페이스를 제공하여 하드웨어 자원에 대한 안전한 접근을 가능하게 합니다.
