### ISSUE TITLE
3주차 주제(운영체제, 네트워크)

### ISSUE THREAD

**Issue by hye-on** [Newbiz-Coders/CStudy#21]
### 📌 네트워크
- [x] [월] : UDP에서 멀티 캐스트와 브로드캐스트에 대해 간략히 설명해주세요
- [ ] [목] : 대칭키와 공개키의 차이에 대해 설명해주세요.

### 📌 운영체제
- [x] [화] : **컨텍스트 스위칭**은 무엇이고, 이 과정에서 **PCB**는 어떤 역할을 하는지 설명해주세요.
- [ ] [목] : IPC의 대표적인 모델 2가지에 대해 알려주세요

**Comment by emoee** [comment]
### 대칭키와 공개키 같이 사용하는 이유?
대칭키는 키가 같아 속도가 빠르지만 키를 공유하는 과정에서 보안 문제가 발생할 수 있습니다. 하지만 공개키는 보안성은 높으나 속도가 느리게 됩니다. 따라서 결합하여 사용하게되는데 공개키로 대칭키를 공유하고 데이터 전송에 사용하게 됩니다. 이로 보안성, 효율성을 지키게 됩니다.

**Comment by devstar1223** [comment]
## 공개키 암호화 활용 사례 - 전자서명

### 메세지 해시 값 계산

- 서명하려는 메세지(문서 파일 등) 에 대한 **해시 값을 생성**한다.
- 원본 메세지의 무결성을 보장한다. → 메세지 내용이 변경되면 해시 값도 달라짐

### 해시 값에 개인키로 서명

- 서명자는 **자신의 개인키**를 사용해 계산된 메세지 해시 값을 암호화 한다.
    - 이 암호화된 해시값이 바로 **전자 서명**
- 개인키는 비밀로 유지되어, 이 개인키로만 데이터를 서명할 수 있다.
- 서명자는 **서명된(암호화된) 해시 값**과 **원본 메세지**를 함께 보낸다.

### 서명 검증

- 메시지를 수신한 사람은 서명 검증을 해야한다.
    - 원본 메세지에 다시 해시값을 계산한다.
        - 이 값이 보낸 메세지와 동일해야 한다.(틀릴 경우, 중간에 위조/변조 된것.)
    - **서명된(암호화된) 해시 값** 을 **서명자의 공개키**를 사용해 복호화 한다.
        - 복호화된 값은 메세지에 대해 계산한 원본 해시값 이어야 한다.

### 검증 결과

- 복호화된 해시 값과 수신자가 새로 계산한 해시 값이 같다면, 메세지는 변조되지 않은것.
- 두 해시 값이 일치하지 않으면, 메세지가 변조되었거나 서명이 위조되었다.

**Comment by hye-on** [comment]
Q1: "대칭키 암호화의 대표적인 알고리즘은 무엇인가요?"
A: "AES가 가장 대표적이며, DES와 3DES도 있지만 현재는 보안 강도 때문에 AES를 주로 사용합니다."

**Comment by SemiHyeon** [comment]
### 공개키 암호화 방식의 주요 알고리즘에 대해 설명해주세요
대표적인 공개키 암호화 알고리즘으로는 RSA와 ECC가 있습니다. RSA는 정수 분해 문제를 기반으로 하며, ECC는 타원곡선 이론을 기반으로 RSA보다 짧은 키 길이로 높은 보안을 제공합니다.

**Comment by devstar1223** [comment]
## 공유 메모리 모델 동기화 문제 해결법

### 세마포어

- 공유 자원에 접근할 수 있는 허용 가능한 동시 실행 수를 제한하는 **카운터**
    - 특정 값(N)을 설정하여 최대 N개의 스레드가 동시에 자원에 접근할 수 있도록 제한한다.
- 동작 방식
    1. 자원에 접근하기 전에 `P` (wait) 연산을 호출하여 세마포어 값을 감소 시킨다.
    2. 작업이 끝나면 `V` (signal) 연산을 호출하여 세마포어 값을 증가시킨다.
    - 세마포어 값이 0이면, 다른 스레드는 대기 상태에 들어간다.
- DB 연결 풀과 같이 제한된 리소스를 여러 스레드가 사용하는 경우 사용한다.
- 주차장에 **최대 N대의 차량만 입장할 수 있는 입구 관리 시스템**이라 할 수 있다.

### 뮤텍스

- 단일 스레드만 공유 자원에 접근할 수 있도록 보장하는 **락(Lock)**
- 한 번에 오직 하나의 스레드만 뮤텍스를 획득하고 자원을 사용할 수 있다.
- 뮤텍스를 해제하지 않으면 다른 스레드가 자원에 접근할 수 없다.
- 동작 방식
    1. 자원을 사용하려는 스레드는 **뮤텍스를 획득(lock)** 한다.
    2. 자원 사용이 끝나면 **뮤텍스를 해제(unlock)** 한다.
    - 뮤텍스는 반드시 락을 획득한 스레드가 해제해야 한다.
- 파일 쓰기, 데이터 변경과 같은 임계구역을 보호할때 주로 사용한다.
- 화장실 **문을 잠가 한 사람만 사용할 수 있도록 하는 잠금 장치** 라고 할 수 있다.

**Comment by emoee** [comment]
IPC 동기식, 비동기식 통신의 차이는?
동기식 통신은 송신자가 메세지를 보내고 수신자가 처리할 떄 까지 기다리는 방식으로 메세지 처리가 완료된 것을 확인하고 다음 작업을 수행합니다. 따라서 순차적이며 속도가 상대적으로 느립니다.
비동기식은 송신자는 메세지를 보내기만하고 수신자가 별도로 메세지를 처리하기 때문에 효율적이며 속도가 빠릅니다.

**Comment by hye-on** [comment]
Q2: "메시지 전달 방식의 종류에는 어떤 것들이 있나요?"
A: "파이프, 메시지 큐, 소켓등이 있습니다. 파이프는 단방향 통신, 메시지 큐는 양방향 비동기 통신, 소켓은 네트워크 통신까지 가능한 방식입니다."

**Comment by sungmingt** [comment]
Q1 : 꼬리질문 HTTPS에서 대칭키와 비대칭키를 어떻게 사용하나요?

A1 : HTTPS에서는 client와 server가 데이터를 암호화하여 주고받기 위해 비대칭키 방식과 대칭키 방식을 혼용하여 사용하는데, 데이터를 주고받을때는 기본적으로 속도가 빠른 대칭키 방식을 사용하지만, 처음 대칭키를 주고받을때는 안전하게 비대칭키 방식으로 주고받는다 -> 하이브리드 방식

Q2 : 메시지 전달 모델의 종류 중 Indirect Communication에 대해 설명해주세요

A2 : mailbox(또는 port)를 통해 메시지를 간접 전달하는 방식으로, port로 전송만 하면 되기 때문에 복잡한 Communication Link를 만들 수 있으며, 다대다 관계가 가능합니다.  예를 들어 A 프로세스가 B 프로세스에게 메시지를 전달하고 싶을 때, 커널 내부 특정 포트에 메시지를 저장해 놓고, B 프로세스가 해당 포트에 접근하여 메시지를 받는 방식입니다.
