### ISSUE TITLE
4주차 주제(Race Condition, TLS/SSL handshake)

### ISSUE THREAD

**Issue by hye-on** [Newbiz-Coders/CStudy#44]
### 📌 네트워크
- [x] [월] : **HTTP**는 어떤 상황에서 사용되며, **HTTPS**는 어떤 상황에서 필수적이라고 생각하나요?
- [x] [목] : TLS/SSL handshake에 대해 설명해주세요

### 📌 운영체제
- [x] [화] : CPU 스케줄링에서 **선점 스케줄링과 비선점 스케줄링의 차이**를 설명해주세요.
- [x] [목] : Race Condition이 언제 발생할까요?

**Comment by devstar1223** [comment]
## 현대 운영체제에서는 무엇을 사용할까?

- 대부분 **선점 스케줄링**을 사용한다.

### 사용 이유

- 멀티태스킹 환경에서 여러 프로세스를 효율적으로 관리할 수 있다.
    - CPU 자원을 공평하게 분배 가능하여, 높은 응답 시간을 요구하는 실시간 시스템에서도 유리하다.
- 스마트폰, 서버, 데스크탑 등 현대적인 운영체제는 실시간성을 중시하는 경우가 많다.

**Comment by sungmingt** [comment]
Q : 선점/비선점의 우선순위 알고리즘의 문제 해결 방법 중 하나인 에이징에 대해서 설명해주세요

A : 실행 준비가 되었으나 우선순위가 높은 프로세스가 계속 들어오면 우선순위가 낮은 프로세스는 무한정 대기해야 하는 상황이 발생하는데,
에이징은 매 분마다 대기 중인 프로세스의 우선순위를 1씩 증가시킴으로써 문제를 해결하는 방식입니다.

**Comment by SemiHyeon** [comment]
## 선점 스케줄링을 사용할 때 발생할 수 있는 문제는 무엇인가요?
기아문제가 발생할 수 있습니다. 낮은 우선순위를 가진 프로세스가 높은 우선순위 프로세스가 계속 도착할 경우 무기한 대기 상태에 놓일 수 있습니다. 이를 해결하기 위해 에이징(Aging) 기법을 사용해 낮은 우선순위 프로세스의 우선순위를 점진적으로 높이는 방식이 활용됩니다.

**Comment by hye-on** [comment]
Q. Handshake가 완료되었음을 어떻게 보장하나요?

A. Handshake 과정의 마지막 단계에서 클라이언트와 서버는 교환된 모든 메시지를 해싱하고, 이를 대칭키로 암호화하여 Finished 메시지로 교환합니다. 각자 복호화한 결과가 동일하다면 Handshake가 성공적으로 완료되었음을 확인할 수 있습니다.

**Comment by emoee** [comment]
TLS/SSL 핸드셰이크에서 클라이언트가 서버 인증서를 검증방법은?

클라이언트는 서버의 인증서를 받아 인증서 내 공개키와 인증기관(CA)의 서명을 확인합니다. 이 서명을 검증하여 서버의 신뢰성을 판단하며, CA 인증서 체인을 통해 최상위 루트 CA까지 확인하여 인증서를 신뢰할 수 있는지 최종 판단합니다.

**Comment by WARDKEY** [comment]
TLS/SSL 핸드쉐이크의 목적은 무엇인가요?

데이터가 전송되는 동안 암호화를 적용하여 기밀성을 유지할 수 있으며, 무결성이 보장되고,

인증 과정을 통해 클라이언트와 서버의 신원을 확인하여 신뢰할 수 있는 통신을 보장합니다.

**Comment by SemiHyeon** [comment]
**TLS 핸드셰이크에서 사용하는 암호화 알고리즘은 어떤 종류가 있나요?**

답변: 핸드셰이크 과정에서는 비대칭 키 암호화(예: RSA, ECDSA)가 사용되어 세션 키를 안전하게 교환합니다. 이후 데이터 전송은 대칭 키 암호화(예: AES)로 처리됩니다. 최신 TLS에서는 키 교환을 위해 Diffie-Hellman 알고리즘도 사용됩니다.

**Comment by hye-on** [comment]
Q.
멀티 프로세서 환경에서 Lock 없이 Race Condition을 해결할 수 있는 방법이 있나요?

A.
Lock-Free 프로그래밍 기법이나 Atomic 연산을 활용하면 공유 자원 접근 시 Lock 없이도 Race Condition을 해결할 수 있습니다.

**Comment by hye-on** [comment]
Q. 문맥 교환 중 Race Condition을 방지하려면 어떻게 해야 하나요?

A. 문맥 교환 중 Race Condition을 방지하기 위해 커널 모드에서 작업 중에는 시간을 초과하더라도 CPU 제어권을 다른 프로세스에 넘기지 않도록 설정합니다.

**Comment by WARDKEY** [comment]
Race Condition의 방지 방법은 무엇이 있나요?

뮤텍스와 세마포어, 락과 같은 동기화 메커니즘을 사용하여 한 번에 하나의 프로세스 또는 스레드가 자원에 접근할 수 있도록 할 수 있습니다.

**Comment by emoee** [comment]
경쟁상태와 데드락의 차이점은 무엇인가요?

경쟁상태는 공유 자원의 접근 순서가 달라져 결과가 비정상적으로 변경되는 상황입니다. 반면, 데드락은 두 개 이상의 프로세스가 서로가 점유한 자원을 기다리며 무한히 정지되는 상태를 말합니다. 경쟁상태는 실행 순서 문제지만, 데드락은 자원 대기 문제로 인해 진행이 불가능한 차이가 있습니다.

**Comment by emoee** [comment]
경쟁상태가 발생할 수 있는 시점을 어떻게 감지할 수 있나요?

경쟁상태는 실행 결과가 비정상적일 때 감지할 수 있습니다. 이를 방지하려면, 테스트 환경에서 의도적으로 프로세스를 병렬 실행하여 동기화 문제를 유발하는 방식으로 테스트합니다. 또한, 데드락 탐지 알고리즘과 유사한 도구로 로그를 분석해 경쟁상태를 발견할 수도 있습니다.

**Comment by devstar1223** [comment]
### TLS/SSL 핸드셰이크와, 암호화 통신이 설정된 이후 서버-클라이언트간 데이터 전송엔 각각 어떤 암호화 기법이 쓰이나요?

- TLS/SSL 핸드셰이크는 **비대칭키 암호화 방식**을 사용하여 안전한 암호화 통신을 설정합니다.
- 이후 암호화 통신이 설정되면, 생성된 **대칭키**인 세션키 기반으로 서로 데이터를 암호화하고 복호화합니다.

---

### HTTPS 통신에서 TLS 핸드셰이크가 필수적인 이유는 무엇인가요?

- TLS 핸드셰이크 과정중 암호화된 통신을 설정하여 데이터가 도청되거나 변조되지 않도록 한다.
- TLS 핸드셰이크중 서버는 디지털 인증서를 클라이언트에 제공함으로써, 클라이언트는 서버가 신뢰할 수 있는 검증된 서버인지 확인 가능하다.

---

### Race Condition과 Deadlock의 차이점은 무엇인가요?

- Race Condition은 여러 프로세스가 동시에 동일한 자원에 접근하여, 접근 순서가 실행 결과에 영향을 미치는 상황에 발생해, 데이터 불일치나 시스템 오류를 초래할 수 있는 현상입니다.
- 반면에 Deadlock은 두 프로세스가 각각의 자원을 점유중이고, 서로 다른 프로세스가 가지고 있는 자원이 필요할때 서로 무한히 대기하는 현상으로, 교착 상태에 빠져 더이상 시스템이 진행되지 못합니다.

---

### Race Condition이 해결되지 않을 경우 발생할 수 있는 일은 무엇이 있을까요?

- 여러 스레드 또는 프로세스가 동시에 동일한 데이터에 접근 및 수정하면서, 수정된 결과가 의도치 않게 덮어쓰이거나 잘못된 값으로 저장될 수 있습니다. 이로 인해 데이터 무결성이 깨지게 됩니다.

**Comment by emoee** [comment]
동기 + 블로킹: 간단한 I/O 작업, 작업 완료 전 다른 작업 실행 불가.

7. 블로킹과 논블로킹이 성능에 미치는 영향은?
    
    블로킹 방식은 대기 시간이 길어질 수 있지만 간단한 구현이 가능하며, 논블로킹은 병렬 작업 처리로 성능이 개선될 수 있지만 구현이 복잡합니다.
