### ISSUE TITLE
5주차 주제(운영체제, 네트워크)

### ISSUE THREAD

**Issue by devstar1223** [Newbiz-Coders/CStudy#65]
📌 네트워크
- [x]  [월] : 로드밸런싱의 역할은 무엇인가요?
- [x]  [목] : 동기/비동기와 블로킹/논블로킹의 관계와 차이점에 대해 설명해주세요

📌 운영체제
- [x]  [화] : 뮤텍스와 세마포어의 차이에 대해 설명해주세요.
- [x]  [목] : 페이징과 세그먼테이션의 주요 차이점은 무엇인가요?

**Comment by WARDKEY** [comment]
질문 : 로드밸런싱 알고리즘 대표적인 두 가지를 설명

답변 : 라운드 로빈 방식이 있으며 서버의 요청을 순서대로 처리하는 방식이다.

최소 연결법이 있으며 현재 연결 수가 가장 적은 서버에 트래픽을 분배하는 방식으로 서버의 성능과 요청 시간이 다를때 사용한다.

질문 : 소프트웨어 로드밸런싱과 하드웨어 로드밸런싱의 차이

답변 : 소프트웨어는 클라우드 환경에서 주로 사용된다.
하드웨어는 장비를 사용해서 확장성이 떨어지고 요즘은 소프트웨어 로드밸런싱을 많이 사용하고 웹 서버로 Nginx를 많이 사용한다.

**Comment by hye-on** [comment]
Q. Node.js가 비동기-논블로킹 방식을 채택한 이유는 무엇인가요?
A. Node.js는 단일 스레드로 동작하면서도 높은 처리량을 달성하기 위해 비동기-논블로킹 방식을 채택했습니다. 이벤트 루프를 통해 I/O 작업을 비동기적으로 처리하며, 작업이 완료될 때까지 기다리지 않고 다른 요청을 처리할 수 있어 서버의 효율성이 높아집니다. 특히 많은 동시 접속자를 처리해야 하는 실시간 애플리케이션에서 큰 장점을 가집니다.

**Comment by hye-on** [comment]
Q. 비동기 프로그래밍의 주의점은 무엇인가요?

A. 순서 보장: Promise.all 등을 활용하여 필요한 경우 작업 순서를 제어해야 합니다.

**Comment by devstar1223** [comment]
## 질문 1 : 비동기 + 블로킹 방식은 왜 잘 사용되지 않을까?

- 비동기 방식의 장점은 다른 작업을 기다리지 않고 동시에 처리 가능 하다.
    - 대기 시간을 최소화 하고, 한 작업이 끝날 때까지 다른 작업을 처리할 수 있어 효율적이다.
- 블로킹 방식은 작업이 완료될 때 까지 대기해야 한다.
    - 비동기 방식의 장점인 “다른 작업 동시 처리” 능력이 제한된다.
- 비동기의 장점을 제대로 활용하지 못해, 성능 저하를 초래한다.

## 질문 2 : 웹 서버에서 비동기 처리를 사용하는 이유?

- 하나의 스레드가 여러 작업을 처리할 수 있게 함으로써, 스레드를 낭비하지 않고 자원을 효율적으로 사용할 수 있다.
- 요청을 처리하는 동안 다른 작업을 동시에 진행할 수 있기 떄문에, 더 많은 요청을 처리할 수 있다.
- 결론적으로, 더 많은 요청을 동시에 처리하면서 자원 효율성을 높이기 때문에 응답 시간을 줄일 수 있다는 장점이 있다.

**Comment by SemiHyeon** [comment]
## 비동기 방식에서 블로킹을 피할 수 없는 상황이 있나요?

답변: 네, 비동기 방식에서도 블로킹을 피할 수 없는 경우가 있습니다. 예를 들어, 파일 입출력, 데이터베이스 쿼리, 외부 시스템과의 동기적 통신 등은 결과를 받아오기 전에 기다려야 하는 상황이 발생할 수 있습니다.

## 블로킹과 논블로킹의 예시를 들어주세요.

블로킹의 예시는 파일 입출력, 데이터베이스 쿼리가 있으며,

논블로킹은 서버의 이벤트 루프가 있습니다. 이벤트가 발생하는 동안 다른 작업을 동시에 처리할 수 있어 서버가 멈추지 않고 계속해서 다른 요청을 처리할 수 있습니다.

**Comment by hye-on** [comment]
Q. 페이지 테이블과 세그먼트 테이블의 주요 차이점은 무엇인가요?

A. 페이지 테이블은 각 항목이 고정 크기여서 인덱스로 직접 접근이 가능하고, 페이지 번호와 프레임 번호만 관리합니다. 반면 세그먼트 테이블은 가변 크기라서 전체 테이블 검색이 필요하며, 세그먼트의 길이와 접근 권한 등 추가 정보도 관리합니다.

**Comment by devstar1223** [comment]
# 추가 질문

## 질문 1 : 각각의 관리기법에서 발생할 수 있는 문제점과 해결법은?

- 페이징 기법 : **내부 단편화**
    - 고정적인 단위로 나뉜 페이지에, 페이지보다 훨씬 적은 메모리를 차지하는 프로세스가 할당되면 메모리의 낭비가 심해지는 내부 단편화 문제가 발생합니다.
    - **페이지의 크기를 작게 조정**하여 내부 단편화를 줄일수 있으나, 메모리 관리가 복잡해지고 시스템 성능이 저하될 수 있습니다.
- 세그먼테이션 기법 : **외부 단편화**
    - 여러 개의 프로세스가 메모리를 할당받고 해제되면서, 메모리 상에 빈 공간이 여러 군데 생기게되고, 분산되어 있어서 새로운 프로세스가 메모리를 사용하지 못하는 문제
    - 메모리 상의 빈 공간을 모아서 연속적인 큰 공간을 만드는 **압축 기법**이 있으나, 메모리 상에서 프로세스를 다시 배치해야 하기 떄문에 메모리 관리가 복잡해지고, 오버헤드가 발생합니다.

## 질문 2 : 페이지폴트와 페이지 교체 알고리즘을 설명해 주세요.

- 페이지 폴트
    - 프로그램이 실행 중에 필요한 페이지가 RAM 에 없을 경우 발생하는 이벤트
    - 프로세스가 요구한 페이지가 물리적 메모리에서 찾아지지 않으면 페이지 폴트가 발생한다.
- 페이지 교체 알고리즘은, 페이지 폴트가 발생했을때 물리적 메모리에 저장되어야 할 페이지를 선택하는 방식
- 어떤 페이지를 교체할지 결정하는 방식에 따라 다르다.
    - FIFO : 가장 먼저 들어온 페이지를 가장 먼저 교체
    - LRU : 가장 오랫동안 사용되지 않은 페이지를 교체
    - OPT : 최적 알고리즘. 미래에 가장 오래 사용되지 않을 페이지를 교체

**Comment by emoee** [comment]
내부 단편화와 외부 단편화의 차이는?
내부 단편화: 메모리 블록 내부의 사용되지 않는 공간
외부 단편화: 사용되지 않는 메모리 블록들이 흩어져서 사용할 수 없는 상황

세그먼테이션의 사용?
함수, 데이터, 코드 같은 논리적 단위로 메모리를 구분해야 하는 경우에 적합합니다.

**Comment by SemiHyeon** [comment]
## 두 기법 중 어느 것이 더 효율적인가요?
페이징과 세그멘테이션은 각각의 장단점이 있어 환경과 요구 사항에 따라 다릅니다.
페이징은 메모리를 고정된 크기로 나누기 때문에 단편화를 줄이고, 메모리를 효율적으로 관리하기 좋습니다
세그멘테이션은 개발자나 사용자 입장에서 이해하기 쉬운 장점이 있지만, 외부 단편화로 인해 메모리 활용률이 낮아질 수 있습니다.
상황에 따라 선택하는 것이 좋으며 둘을 결합한 방식을 사용하는것도 좋은 방법입니다.

## 세그멘테이션에서 외부 단편화는 왜 발생하나요?
세그멘테이션은 세그먼트 크기가 가변적이기 때문에, 메모리 상에서 연속적인 공간이 부족하면 외부 단편화가 발생합니다
