### ISSUE TITLE
6주차 주제(운영체제, 네트워크)

### ISSUE THREAD

**Issue by hye-on** [Newbiz-Coders/CStudy#85]
📌 네트워크
- [x]  [목] : Blocking I/O와 Non-Blocking I/O의 정의와 차이점에 대해 설명해 주세요

📌 운영체제
- [x]  [월] : 페이지폴트와 페이지 교체 알고리즘을 설명해 주세요.
- [x]  [화] : 파일 시스템에서 '마운트(Mount)'의 개념은 무엇이며, 왜 중요한가요?
- [x]  [목] : CPU, 메인 메모리, 캐시 메모리의 관계와 MMU의 역할에 대해 설명해주세요.

**Comment by devstar1223** [comment]
## FIFO 보다 LRU가 더 많이 사용되는 이유

### 메모리 효율적인 교체 방식

- FIFO는 단순히 들어온 순서대로 페이지를 교체하지만, LRU는 최근에 자주 사용된 페이지는 메모리에 남기고, 오랫동안 사용되지 않은 페이지를 교체하기 때문

### Belady’s anomaly 회피

- 메모리 크기를 늘렸을 떄, 페이지 폴트가 오히려 증가하는 현상
- FIFO 방식은 미래의 참조를 예측하지 않기 떄문에 발생한다.

**Comment by SemiHyeon** [comment]
### 페이지 교체 알고리즘 중 FIFO OPT LRU에 대해서 설명해주세요
FIFO 는 가장 먼저 메모리에 들어온 페이지를 가장 먼저 교체하는 알고리즘이며, OPT는 가장 오래 사용되지 않을 페이지를 교체하는 알고리즘입니다. LRU는 가장 오래 사용되지 않은 페이지를 교체하는 알고리즘입니다.

+  opt는 이론상 최적이지만 미래 접근 예측이 어려워 실용적이지 않고, LRU는 실제 사용하는 패턴에 적합하여 페이지 폴트를 줄이는데 표과적입니다.

**Comment by hye-on** [comment]
#### 페이지 교체가 자주 발생하면 시스템 성능에 어떤 영향을 미치나요?

디스크 I/O가 증가해 시스템 성능이 저하되며, CPU가 실제 작업보다 페이지 교체 작업에 시간을 더 많이 소모합니다. 스래싱으로 이어질 수 있으며, 전체 시스템 처리량이 감소합니다.

**Comment by emoee** [comment]
파일 시스템의 단편화란?
단편화 : 파일이 디스크 공간에 연속적으로 저장되지 못하고 조각나게 되는 현상
파일 접근 속도를 저하시킬 수 있으며, 이를 해결하기 위해 디스크 조각 모음(Defragmentation)이 필요

**Comment by SemiHyeon** [comment]
## 마운트와 언마운트의 차이점에 대해 설명해주세요.
마운트는 저장 장치를 운영체제의 특정 디렉토리에 연결하여 사용할 수 있게 만드는 과정이며,
언마운트는 마운트된 장치를 안전하게 운영체제에서 분리하는 작업입니다.

**Comment by hye-on** [comment]
파일 시스템의 특징과 역할에 대해 알려주세요.

특징

커널 영역에서 동작
파일 CRUD 기능을 원활히 수행하기 위한 목적
계층적 디렉터리 구조를 가짐
디스크 파티션 별로 하나씩 둘 수 있음

역할

파일 관리
보조 저장소 관리
파일 무결성 메커니즘
접근 방법 제공
개발 목적

**Comment by sungmingt** [comment]
## 잘못된 마운트 옵션을 사용하면 어떤 문제가 발생할 수 있나요?

마운트 옵션은 파일시스템의 동작 방식을 지정하는 설정으로, 데이터를 어떻게 읽고 쓰는지, 어떤 접근 권한을 허용하는지 등을 제어합니다.
이때 적절하지 않은 마운트 옵션을 설정하면 데이터 접근이 불가능해지거나 보안 문제가 발생할 수 있기 때문에 주의해야 합니다.

**Comment by emoee** [comment]
페이지 교체 필요 이유
페이지 교체 : 메모리가 부족할 때, 메모리에서 일부 페이지를 디스크로 옮기고 새 페이지를 메모리로 가져오는 과정
페이지 폴트가 발생하면, 시스템은 페이지 교체 알고리즘을 통해 메모리 부족 문제를 해결, 많은 메모리 공간을 프로세스 제공 가능

캐시 메모리 필요 이유
CPU와 메인 메모리 사이의 속도 차이를 줄이기 위해 사용

**Comment by devstar1223** [comment]
## 질문 1 : CPU가 캐시 메모리에 어떤 데이터를 어떤 기준으로 저장하나요?

- 지역성을 기반으로 데이터를 저장합니다.
- 시간 지역성
    - 최근에 사용된 데이터는 다시 사용될 가능성도 높다는 원리입니다.
- 공간 지역성
    - 특정 데이터에 접근하면, 그와 가까운 주소의 데이터에도 접근할 가능성이 높다는 원리입니다.

## 질문 2 : 캐시 미스가 발생할때의 과정을 알려주세요

1. CPU가 특정 데이터에 접근하기 위해 캐시 메모리를 검색합니다.
2. 캐시에 요청한 데이터가 없는 경우 캐시미스가 발생합니다.
3. CPU가 메인 메모리로 접근합니다.
4. 메인 메모리는 요청된 데이터와 인접한 데이터를 캐시 블록 단위로 읽어옵니다.
    - 캐시 블록 : 캐시 메모리에서 데이터를 저장하는 기본 단위
5. 메모리에서 읽어온 데이터를 캐시 메모리에 저장합니다.
6. 캐시에 데이터가 저장된 후, CPU는 캐시에서 데이터를 읽어옵니다.

**Comment by emoee** [comment]
Non-Blocking I/O 방식이 효율적인 이유는?
Non-Blocking I/O는 커널 작업이 완료되지 않아도 User Process가 다른 작업을 수행할 수 있어 CPU 자원을 효율적으로 사용할 수 있다. I/O 작업이 준비되었을 때만 데이터를 복사하기 때문에 불필요한 대기 시간이 줄어든다.

Blocking I/O와 Non-Blocking I/O는 각각 어떤 환경에서 적합한가?
Blocking I/O : 동기 작업이 주로 이루어지는 단순한 프로그램
Non-Blocking I/O : 대규모 네트워크 서버나 비동기 작업이 필요한 환경

**Comment by devstar1223** [comment]
## 질문 1 : 어떤 상황에서 각 방식을 선택하는 것이 더 적합할까?

### Blocking I/O 선택

- 동시 작업이 많지 않고, 구현의 단순성과 유지보수가 중요한 경우
- 작업이 순차적으로 처리되거나 동기적인 흐름이 중요한 경우

### Non-Blocking I/O 선택

- 다수의 동시 요청을 효율적으로 처리해야 하는 경우
- 네트워크 기반 애플리케이션에서 높은 확장성이 요구되는 경우

## 질문 2 : Non-Blocking I/O 사용시, I/O 작업 완료 여부를 프로세스가 알 수 있는 방법?

- 작업 완료 여부는 폴링, 이벤트 기반 모델, 비동기 콜백 메커니즘을 통해 확인 가능하다.

### 폴링

- 프로세스가 주기적으로 작업 완료 여부 확인
- I/O 작업 요청 후, 데이터를 사용할 준비가 되었는지 지속적인 확인

### 이벤트 기반 모델

- 이벤트 루프가 I/O 작업 완료 여부 감시
    - 작업이 완료 되었을 때, 이벤트 루프가 해당 작업을 처리하거나 지정된 콜백 함수 호출 → 폴링의 비효율성 개선

### 비동기 콜백

- I/O 작업 요청시 콜백 함수를 등록하여, 작업이 완료되면 해당 함수가 실행되도록 하는 방식

**Comment by SemiHyeon** [comment]
### Q. MMU가 가상 주소를 물리 주소로 변환하는 과정에 대해 설명해 주세요
A. MMU는 가상 주소를 물리 주소로 변환하기 위해 페이지 테이블(Page Table)을 사용합니다. 각 프로세스는 가상 메모리 주소를 할당받고, MMU는 이 주소를 실제 메모리 주소인 물리 주소로 변환합니다. 페이지 테이블에는 가상 주소와 물리 주소의 매핑 정보가 저장되어 있어, MMU는 이를 통해 변환을 수행합니다

### Q. TLB가 필요한 이유는 무엇인가요
A. CPU가 메모리 접근 시, 페이지 테이블을 매번 참조하면 속도가 느려지기 때문에, TLB를 활용해 필요한 정보를 빠르게 조회할 수 있습니다

---

### Q. Non-Blocking I/O가 항상 더 좋은 선택인가요?
A. 논블로킹 I/O는 복잡성과 디버깅 비용이 증가할 수 있기 때문에 단순한 애플리케이션에서는 Blocking I/O로 충분히 효율적이고 안정적인 처리가 가능합니다.

### Q. Non-Blocking I/O를 사용하는 주요 사례는 무엇인가요?
A. 채팅 서버와 같은 실시간 데이터 처리나, 대규모 요청 처리, 동영상 스트리밍 같은 서비스에서 사용됩니다.
